version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:12 # ...with this image as the primary container; this is where all `steps` will run
      
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - restore_cache:
            keys:
                - v1-repo-{{ checksum "yarn.lock" }}

      # Install Deps
      - run:
          name: Install Deps
          command: yarn install --frozen-lockfile

          
      - run:
          name: Build Project
          command: yarn build

      - run:
            name: Run tests
            command: yarn test

      - store_artifacts:
            path: test-results

      - store_test_results:
            path: test-results